'use client';
import { useState } from 'react';
const examples = [
  {name:'Maya',initial:'M',treatment:'Clear aligners',question:'I’m interested in clear aligners. Could I speak to someone after work?',preference:'Weekday evenings',note:'Asked for a conversation after work. Dentist to assess suitability.'},
  {name:'Sam',initial:'S',treatment:'Dental implants',question:'I’d like to understand the consultation process for a missing tooth.',preference:'Morning callback',note:'Wants to understand the initial consultation. No suitability assessment has been made.'},
  {name:'Alex',initial:'A',treatment:'General consultation',question:'I’m new to the clinic. How do I arrange a first visit?',preference:'Weekend preference',note:'New visitor asking about a first appointment. Team to confirm availability.'},
];
const stages = ['Enquiry','Team handoff','Follow-up','Outcome'];
export default function RevenueWalkthrough() {
  const [scenario,setScenario] = useState(0);
  const [step,setStep] = useState(0);
  const [outcome,setOutcome] = useState<'booked'|'later'|null>(null);
  const sample = examples[scenario];
  function reset(index = scenario) {setScenario(index);setStep(0);setOutcome(null);}
  return <section className="workflow-section" id="workflow"><div className="clinic-shell"><div className="section-heading"><div><p className="kicker">FOR THE CLINIC TEAM / TRY IT YOURSELF</p><h2>A website enquiry.<br /><em>Now with a next step.</em></h2></div><p>Keep your existing website. Explore how RevenueOS could connect the conversation to your team’s daily follow-up.</p></div>
    <div className="walkthrough"><div className="walkthrough-top"><span><i aria-hidden="true"/> REVENUE<span className="os-mark">OS</span> / INTERACTIVE TOUR</span><span className="simulation-label">Fictional data · Local simulation</span></div>
      <div className="scenario-picker" aria-label="Choose a sample enquiry">{examples.map((item,index)=><button key={item.name} onClick={()=>reset(index)} aria-pressed={scenario===index}><span>{item.initial}</span><span>{item.treatment}<small>{item.name}’s enquiry</small></span></button>)}</div>
      <ol className="walkthrough-progress">{stages.map((stage,index)=><li key={stage} className={index===step?'current':index<step?'complete':''}><span>{index<step?'✓':String(index+1).padStart(2,'0')}</span>{stage}</li>)}</ol>
      <div className="walkthrough-body"><div className="sample-conversation"><span className="sample-label">THE VISITOR’S SIDE</span><div className="sample-avatar">{sample.initial}</div><h3>Meet {sample.name}.</h3><p className="sample-question">“{sample.question}”</p><div className="sample-reply">A team member can help arrange a consultation. What time would suit a callback?</div><p className="sample-preference">{sample.preference} <span>✓</span></p><small>Scripted example. No AI call, personal data or message delivery.</small></div>
      <div className="sample-team" aria-live="polite" aria-atomic="true"><span className="sample-label">THE TEAM’S SIDE</span><div className="sample-card"><div className="sample-card-header"><strong>{sample.name} · Sample enquiry</strong><span className="sample-status">{step===0?'Not captured yet':step===1?'New enquiry':step===2?'Follow-up due':outcome==='booked'?'Appointment recorded':'Follow-up retained'}</span></div>
      {step===0?<div className="sample-empty"><span aria-hidden="true">↗</span><h3>A conversation is a beginning.</h3><p>Capture the visitor’s interest and preferred callback time, so the team has a clear starting point.</p></div>:<><dl><div><dt>Interest</dt><dd>{sample.treatment}</dd></div><div><dt>Preference</dt><dd>{sample.preference}</dd></div><div><dt>Next action</dt><dd>{step===1?'Review enquiry and arrange a callback':step===2?'Staff member to contact visitor':outcome==='booked'?'Record confirmed appointment details':'Keep enquiry open for a later conversation'}</dd></div></dl><div className="sample-team-note"><strong>Team note</strong><p>{sample.note}</p></div>{step>=2&&<div className="sample-followup"><span aria-hidden="true">◷</span><div><strong>{step===3&&outcome==='booked'?'Outcome recorded in this tour':'Follow-up added in this tour'}</strong><p>{step===3&&outcome==='booked'?'A staff-recorded outcome can make the enquiry journey measurable.':'The enquiry stays visible until the team takes action.'}</p></div></div>}</>}
      </div><div className="tour-explanation">{step===0?'Start with a visitor’s question.':step===1?'Context travels with the enquiry. Staff can review it before contacting the visitor.':step===2?'A due date gives the team a next action. This demo does not send reminders or messages.':outcome==='booked'?'This shows a staff-recorded outcome, not a calendar booking or proof of conversion improvement.':'Not every enquiry becomes a booking. Keeping the next action visible is useful too.'}</div></div></div>
      <div className="walkthrough-controls"><button className="tour-reset" onClick={()=>reset()}>↻ Restart tour</button><div>{step<2?<button className="c-button" onClick={()=>setStep(step+1)}>{step===0?'Capture sample enquiry':'Set a sample follow-up'} <span aria-hidden="true">→</span></button>:step===2?<><button className="tour-later" onClick={()=>{setOutcome('later');setStep(3);}}>Keep following up</button><button className="c-button" onClick={()=>{setOutcome('booked');setStep(3);}}>Record sample booking <span aria-hidden="true">✓</span></button></>:<a className="c-button" href="#consult">Try the saved enquiry form <span aria-hidden="true">↗</span></a>}</div></div>
    </div><div className="pilot-strip"><div><p className="kicker">A PILOT WITH A PURPOSE</p><h3>Measure it. Then decide.</h3></div><p>A proposed clinic pilot would compare response time, follow-up completion and staff-recorded booking outcomes against a baseline.</p><span>No promised uplift.<br />No invented results.</span></div>
  </div></section>;
}
